version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    container_name: spring-boot-devcontainer
    user: vscode
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MAVEN_OPTS: -Dmaven.repo.local=/home/vscode/.m2/repository
      JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
    # Enable Docker in Docker for Testcontainers
    privileged: true
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devnet
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring_boilerplate
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnet
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - devnet
volumes:
  postgres-data:
  redis-data:
networks:
  devnet:
